### ISSUE TITLE
Broken on 4.1

### ISSUE THREAD

**Issue by Sch1nken** [anatolbogun/godot-smoother-node#3]
Using 4.1 the smoother script is not functioning. Tested with smoothing position/global_position of a node, this results in the node not changing position AT ALL.

My current, uneducated, guess is that it might have to do with the new processing-features.
In addition to `process_priority` there is now  `process_physics_priority`. Also processing can happen on a separate thread now.

I currently don't have much time, but will be able to look into it further next week.

**Comment by Sch1nken** [comment]
Seems to have... fixed itself? I still don't know why or what changed. I'll close this issue :)

**Comment by Rukiri** [comment]
No longer works at all in 4.1.1
